name: Update IP List

on:
  schedule:
    - cron: '0 4 * * 1' # Запуск каждый понедельник в 04:00 UTC
  workflow_dispatch:    # Позволяет запускать процесс вручную через интерфейс GitHub

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Дает права на пуш коммита в репозиторий

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Можно изменить на нужную версию

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate ip-list.json
        run: python main.py

      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add ip-list.json
          git diff --quiet && git diff --staged --quiet || git commit -m "chore: auto-update ip-list.json"
          git push